import psycopg
from entidades import Usuario, Anotacao, Tarefa, Materia

class Servico:

    # BANCO DE DADOS
    def __init__(self, host="localhost", dbname="meubanco", user="meuuser", password="minhasenha", port=5432):
        self.conexao = psycopg.connect(host=host, dbname=dbname, user=user, password=password, port=port)
        self.cursor = self.conexao.cursor()

    def salvar(self):
        self.conexao.commit()
    
    def salvar_consulta(self):
        return self.cursor.fetchall()

    def salvar_consulta1(self):
        return self.cursor.fetchone()

    def fechar(self):
        try:
            self.cursor.close()
        finally:
            self.conexao.close()

    def proximo_codigo(self, tabela):
        self.cursor.execute(f"SELECT COALESCE(MAX(codigo), 0) FROM {tabela}")
        resultado = self.cursor.fetchone()[0]
        if resultado is None:
            return 1
        else:
            return int(resultado) + 1

    # -- DDL --
    def criar_tabelas(self):
        # 1) usuario
        self.cursor.execute("""
        CREATE TABLE IF NOT EXISTS usuario (
            email TEXT PRIMARY KEY,
            nome  TEXT NOT NULL,
            senha TEXT NOT NULL
        );
        """)

        # 2) materia
        self.cursor.execute("""
        CREATE TABLE IF NOT EXISTS materia (
            codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            titulo TEXT NOT NULL,
            descricao TEXT,
            emailUsuario TEXT NOT NULL REFERENCES usuario(email) ON DELETE CASCADE
        );
        """)

        # 3) tarefa
        self.cursor.execute("""
        CREATE TABLE IF NOT EXISTS tarefa (
            codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dataCriacao TIMESTAMPTZ DEFAULT now(),
            dataFinalizacao TIMESTAMPTZ,
            titulo TEXT NOT NULL,
            descricao TEXT,
            status TEXT NOT NULL, -- ex: 'A' ou 'F'
            emailUsuario TEXT NOT NULL REFERENCES usuario(email) ON DELETE CASCADE,
            codigoMateria BIGINT NOT NULL REFERENCES materia(codigo) ON DELETE CASCADE
        );
        """)

        # 4) anotacao 
        self.cursor.execute("""
        CREATE TABLE IF NOT EXISTS anotacao (
            codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dataCriacao TIMESTAMPTZ DEFAULT now(),
            descricao TEXT,
            emailUsuario TEXT NOT NULL REFERENCES usuario(email),
            codigoMateria BIGINT,
            codigoTarefa BIGINT,
            CONSTRAINT fk_anotacao_materia FOREIGN KEY (codigoMateria) REFERENCES materia(codigo) ON DELETE CASCADE,
            CONSTRAINT fk_anotacao_tarefa  FOREIGN KEY (codigoTarefa)  REFERENCES tarefa(codigo) ON DELETE CASCADE,
            CONSTRAINT chk_somente_um_destino CHECK (
                (codigoMateria IS NOT NULL AND codigoTarefa IS NULL) OR
                (codigoMateria IS NULL AND codigoTarefa IS NOT NULL)
            )
        );
        """)
        self.salvar()

    # -- DML --
    def dados_teste(self):
        # usuarios
        self.cursor.execute("""
            INSERT INTO usuario (email, nome, senha)
            VALUES 
             ('joao@email.com', 'João Silva', '123456'),
             ('maria@email.com', 'Maria Souza', '654321')
            ON CONFLICT (email) DO NOTHING;
        """)

        # materias 
        self.cursor.execute("""
            INSERT INTO materia (codigo, titulo, descricao, emailUsuario)
            VALUES
             (1, 'Algoritmos',       'Introdução à lógica de programação e estruturas de repetição.', 'joao@email.com'),
             (2, 'Banco de Dados',   'Modelagem e SQL aplicado.',                                     'joao@email.com'),
             (3, 'Engenharia de Software', 'Conceitos de análise e desenvolvimento.',                 'joao@email.com'),
             (4, 'Estruturas de Dados',    'Listas, pilhas, filas e árvores.',                        'maria@email.com'),
             (5, 'Programação em C',       'Linguagem C aplicada a problemas práticos.',              'maria@email.com')
            ON CONFLICT DO NOTHING;
        """)

        # tarefas
        self.cursor.execute("""
            INSERT INTO tarefa (codigo, dataCriacao, dataFinalizacao, titulo, descricao, status, emailUsuario, codigoMateria)
            VALUES
             (1, now(), NULL, 'Lista de exercícios de Algoritmos', 'Fazer exercícios do capítulo 2.', 'A', 'joao@email.com', 1),
             (2, now(), NULL, 'Trabalho Banco de Dados', 'Criar diagrama ER.', 'A', 'joao@email.com', 2),
             (3, now(), now(), 'Resumo Engenharia de Software', 'Entregar resumo de metodologias.', 'F', 'joao@email.com', 3),
             (4, now(), NULL, 'Implementar lista encadeada', 'Exercício prático em C.', 'A', 'maria@email.com', 4),
             (5, now(), NULL, 'Estudar ponteiros', 'Revisar capítulo de ponteiros.', 'A', 'maria@email.com', 5),
             (6, now(), now(), 'Exercícios Banco de Dados', 'Queries de junção.', 'F', 'maria@email.com', 2),
             (7, now(), NULL, 'Resumo Estruturas de Dados', 'Preparar para prova.', 'A', 'joao@email.com', 4),
             (8, now(), NULL, 'Projeto final C', 'Desenvolver mini sistema em C.', 'A', 'maria@email.com', 5)
            ON CONFLICT DO NOTHING;
        """)

        # anotações 
        self.cursor.execute("""
            INSERT INTO anotacao (codigo, dataCriacao, descricao, emailUsuario, codigoMateria, codigoTarefa)
            VALUES
             (1, now(), 'Resumo sobre estruturas de repetição.', 'joao@email.com', 1, NULL),
             (2, now(), 'Exemplos de SELECT com JOIN.',          'joao@email.com', NULL, 6),
             (3, now(), 'Modelo cascata vs ágil.',                'joao@email.com', NULL, 3),
             (4, now(), 'Resumo de listas encadeadas.',           'maria@email.com', NULL, 4),
             (5, now(), 'Comandos básicos em C.',                 'maria@email.com', 5, NULL),
             (6, now(), 'Checklist final do projeto C.',          'maria@email.com', NULL, 8),
             (7, now(), 'Revisar teoria de filas e pilhas.',      'joao@email.com', NULL, 7),
             (8, now(), 'Dúvidas sobre SQL avançado.',            'maria@email.com', 2, NULL)
            ON CONFLICT DO NOTHING;
        """)
        self.salvar()

    # USUARIO
    def usuario_criar(self, usuario):
        self.cursor.execute(
            "INSERT INTO usuario(email, senha, nome) VALUES (%s, %s, %s) ON CONFLICT (email) DO NOTHING",
            (usuario.email, usuario.senha, usuario.nome)
        )
        self.salvar()

    def usuario_alterar(self, usuario):
        self.cursor.execute(
            "UPDATE usuario SET senha = %s, nome = %s WHERE email = %s",
            (usuario.senha, usuario.nome, usuario.email)
        )
        self.salvar()
    
    def usuario_deletar(self, usuario):
        self.cursor.execute("DELETE FROM usuario WHERE email = %s", (usuario.email,))
        self.salvar()

    def usuarios_listar(self):
        self.cursor.execute("SELECT email, nome, senha FROM usuario")
        return self.salvar_consulta()

    def usuario_1(self, email):
        self.cursor.execute("SELECT email, nome, senha FROM usuario WHERE email = %s", (email,))
        dados = self.salvar_consulta1()
        if dados:
            return Usuario(dados[0], dados[1], dados[2])
        return None

    def usuario_login(self, email, senha):
        self.cursor.execute("SELECT email, nome, senha FROM usuario WHERE email = %s AND senha = %s", (email, senha))
        dados = self.salvar_consulta1()
        if dados:
            return Usuario(dados[0], dados[1], dados[2])
        return None

    # MATERIA
    def materia_criar(self, materia):
        self.cursor.execute(
            "INSERT INTO materia(codigo, titulo, descricao, emailUsuario) VALUES (%s, %s, %s, %s)",
            (materia.codigo, materia.titulo, materia.descricao, materia.emailUsuario)
        )
        self.salvar()

    def materia_alterar(self, materia):
        self.cursor.execute(
            "UPDATE materia SET titulo = %s, descricao = %s, emailUsuario = %s WHERE codigo = %s",
            (materia.titulo, materia.descricao, materia.emailUsuario, materia.codigo)
        )
        self.salvar()
    
    def materia_deletar(self, materia):
        self.cursor.execute("DELETE FROM materia WHERE codigo = %s AND emailUsuario = %s", (materia.codigo,materia.emailUsuario))
        self.salvar()

    def materia_listar(self):
        self.cursor.execute("SELECT codigo, titulo, descricao, emailUsuario FROM materia")
        return self.salvar_consulta()
    
    def materia_1(self, codigo):
        self.cursor.execute("SELECT codigo, titulo, descricao, emailUsuario FROM materia WHERE codigo = %s", (codigo,))
        dados = self.salvar_consulta1()
        if dados:
            return Materia(dados[0], dados[1], dados[2], dados[3])
        return None

    # TAREFA
    def tarefa_criar(self, tarefa):
        self.cursor.execute(
            """
            INSERT INTO tarefa(codigo, titulo, descricao, status, dataCriacao, emailUsuario, codigoMateria)
            VALUES (%s, %s, %s, %s, now(), %s, %s)
            """,
            (tarefa.codigo, tarefa.titulo, tarefa.descricao, tarefa.status, tarefa.emailUsuario, tarefa.codigoMateria)
        )
        self.salvar()

    def tarefa_alterar(self, tarefa):
        self.cursor.execute(
            """
            UPDATE tarefa
               SET titulo = %s, descricao = %s, status = %s, codigoMateria = %s, emailUsuario = %s
             WHERE codigo = %s
            """,
            (tarefa.titulo, tarefa.descricao, tarefa.status, tarefa.codigoMateria, tarefa.emailUsuario, tarefa.codigo)
        )
        self.salvar()
    
    def tarefa_deletar(self, tarefa):
        self.cursor.execute("DELETE FROM tarefa WHERE codigo = %s AND emailUsuario = %s", (tarefa.codigo,tarefa.emailUsuario))
        self.salvar()

    def tarefa_listar(self):
        self.cursor.execute("""
            SELECT codigo, dataCriacao, dataFinalizacao, titulo, descricao, status, emailUsuario, codigoMateria
            FROM tarefa
        """)
        return self.salvar_consulta()
    
    def tarefa_1(self, codigo):
        self.cursor.execute("""
            SELECT codigo, dataCriacao, dataFinalizacao, titulo, descricao, status, emailUsuario, codigoMateria
            FROM tarefa
            WHERE codigo = %s
        """, (codigo,))
        return self.salvar_consulta1()

    # ANOTACAO
    def anotacao_criar(self, anotacao):
        if (anotacao.codigoMateria is not None and anotacao.codigoTarefa is not None) or \
           (anotacao.codigoMateria is None and anotacao.codigoTarefa is None):
            raise ValueError("A anotação deve estar vinculada a uma matéria OU a uma tarefa, nunca ambas ou nenhuma.")

        self.cursor.execute(
            """
            INSERT INTO anotacao (codigo, dataCriacao, descricao, emailUsuario, codigoMateria, codigoTarefa)
            VALUES (%s, now(), %s, %s, %s, %s)
            """,
            (anotacao.codigo, anotacao.descricao, anotacao.emailUsuario, anotacao.codigoMateria, anotacao.codigoTarefa)
        )
        self.salvar()

    def anotacao_alterar(self, anotacao):
        self.cursor.execute(
            """
            UPDATE anotacao
               SET dataCriacao = now(), descricao = %s, codigoMateria = %s, codigoTarefa = %s, emailUsuario = %s
             WHERE codigo = %s
            """,
            (anotacao.descricao, anotacao.codigoMateria, anotacao.codigoTarefa, anotacao.emailUsuario, anotacao.codigo)
        )
        self.salvar()
    
    def anotacao_deletar(self, anotacao):
        self.cursor.execute("DELETE FROM anotacao WHERE codigo = %s AND emailUsuario = %s", (anotacao.codigo, anotacao.emailUsuario))
        self.salvar()

    def anotacao_listar(self):
        self.cursor.execute("""
            SELECT codigo, dataCriacao, descricao, emailUsuario, codigoMateria, codigoTarefa
            FROM anotacao
        """)
        return self.salvar_consulta()
    
    def anotacao_1(self, codigo):
        self.cursor.execute("""
            SELECT codigo, dataCriacao, descricao, emailUsuario, codigoMateria, codigoTarefa
            FROM anotacao
            WHERE codigo = %s
        """, (codigo,))
        return self.salvar_consulta1()


